Worldcharts.mapDataIndex = {
    "Custom": {
        "Africa": "custom/africa.js",
        "Antarctica": "custom/antarctica.js",
        "Asia": "custom/asia.js",
        "Benelux": "custom/benelux.js",
        "British Isles": "custom/british-isles.js",
        "British Isles, admin1": "custom/british-isles-all.js",
        "Canada and United States of America": "custom/usa-and-canada.js",
        "Central America": "custom/central-america.js",
        "Europe": "custom/europe.js",
        "European Union": "custom/european-union.js",
        "Middle East": "custom/middle-east.js",
        "Nordic Countries without Greenland, Svalbard, and Jan Mayen": "custom/nordic-countries-core.js",
        "Nordic Countries": "custom/nordic-countries.js",
        "North America without central": "custom/north-america-no-central.js",
        "North America": "custom/north-america.js",
        "North Atlantic Treaty Organization": "custom/nato.js",
        "Oceania": "custom/oceania.js",
        "Scandinavia": "custom/scandinavia.js",
        "South America": "custom/south-america.js",
        "World continents": "custom/world-continents.js",
        "World with Palestine areas, high resolution": "custom/world-palestine-highres.js",
        "World with Palestine areas, low resolution": "custom/world-palestine-lowres.js",
        "World with Palestine areas, medium resolution": "custom/world-palestine.js",
        "World, Eckert III projection, high resolution": "custom/world-eckert3-highres.js",
        "World, Eckert III projection, low resolution": "custom/world-eckert3-lowres.js",
        "World, Eckert III projection, medium resolution": "custom/world-eckert3.js",
        "World, Miller projection, high resolution": "custom/world-highres.js",
        "World, Miller projection, low resolution": "custom/world-lowres.js",
        "World, Miller projection, medium resolution": "custom/world.js",
        "World, Miller projection, ultra high resolution": "custom/world-highres3.js",
        "World, Miller projection, very high resolution": "custom/world-highres2.js",
        "World, Robinson projection, high resolution": "custom/world-robinson-highres.js",
        "World, Robinson projection, low resolution": "custom/world-robinson-lowres.js",
        "World, Robinson projection, medium resolution": "custom/world-robinson.js"
    },
    "Countries": {
        "United States of America with Territories": "countries/us/custom/us-all-territories.js",
        "United States of America": "countries/us/us-all.js",
        "United States of America, admin2": "countries/us/us-all-all.js",
        "United States of America, admin2, highres": "countries/us/us-all-all-highres.js",
        "United States of America, congressional districts (113th)": "countries/us/custom/us-113-congress.js",
        "United States of America, mainland": "countries/us/custom/us-all-mainland.js",
        "United States of America, small": "countries/us/custom/us-small.js"
    },
    "USA States": {
        "Alabama, admin2": "countries/us/us-al-all.js",
        "Alaska, admin2": "countries/us/us-ak-all.js",
        "Arizona, admin2": "countries/us/us-az-all.js",
        "Arkansas, admin2": "countries/us/us-ar-all.js",
        "California, admin2": "countries/us/us-ca-all.js",
        "Colorado, admin2": "countries/us/us-co-all.js",
        "Connecticut, admin2": "countries/us/us-ct-all.js",
        "Delaware, admin2": "countries/us/us-de-all.js",
        "District of Columbia, admin2": "countries/us/us-dc-all.js",
        "Florida, admin2": "countries/us/us-fl-all.js",
        "Georgia, admin2": "countries/us/us-ga-all.js",
        "Hawaii, admin2": "countries/us/us-hi-all.js",
        "Idaho, admin2": "countries/us/us-id-all.js",
        "Illinois, admin2": "countries/us/us-il-all.js",
        "Indiana, admin2": "countries/us/us-in-all.js",
        "Iowa, admin2": "countries/us/us-ia-all.js",
        "Kansas, admin2": "countries/us/us-ks-all.js",
        "Kentucky, admin2": "countries/us/us-ky-all.js",
        "Louisiana, admin2": "countries/us/us-la-all.js",
        "Maine, admin2": "countries/us/us-me-all.js",
        "Maryland, admin2": "countries/us/us-md-all.js",
        "Massachusetts, admin2": "countries/us/us-ma-all.js",
        "Michigan, admin2": "countries/us/us-mi-all.js",
        "Minnesota, admin2": "countries/us/us-mn-all.js",
        "Mississippi, admin2": "countries/us/us-ms-all.js",
        "Missouri, admin2": "countries/us/us-mo-all.js",
        "Montana, admin2": "countries/us/us-mt-all.js",
        "Nebraska, admin2": "countries/us/us-ne-all.js",
        "Nevada, admin2": "countries/us/us-nv-all.js",
        "New Hampshire, admin2": "countries/us/us-nh-all.js",
        "New Jersey, admin2": "countries/us/us-nj-all.js",
        "New Mexico, admin2": "countries/us/us-nm-all.js",
        "New York, admin2": "countries/us/us-ny-all.js",
        "North Carolina, admin2": "countries/us/us-nc-all.js",
        "North Dakota, admin2": "countries/us/us-nd-all.js",
        "Ohio, admin2": "countries/us/us-oh-all.js",
        "Oklahoma, admin2": "countries/us/us-ok-all.js",
        "Oregon, admin2": "countries/us/us-or-all.js",
        "Pennsylvania, admin2": "countries/us/us-pa-all.js",
        "Rhode Island, admin2": "countries/us/us-ri-all.js",
        "South Carolina, admin2": "countries/us/us-sc-all.js",
        "South Dakota, admin2": "countries/us/us-sd-all.js",
        "Tennessee, admin2": "countries/us/us-tn-all.js",
        "Texas, admin2": "countries/us/us-tx-all.js",
        "Utah, admin2": "countries/us/us-ut-all.js",
        "Vermont, admin2": "countries/us/us-vt-all.js",
        "Virginia, admin2": "countries/us/us-va-all.js",
        "Washington, admin2": "countries/us/us-wa-all.js",
        "West Virginia, admin2": "countries/us/us-wv-all.js",
        "Wisconsin, admin2": "countries/us/us-wi-all.js",
        "Wyoming, admin2": "countries/us/us-wy-all.js"
    },
    "USA congressional districts (113th)": {
        "Alabama congressional districts": "countries/us/custom/us-al-congress-113.js",
        "Alaska congressional districts": "countries/us/custom/us-ak-congress-113.js",
        "American Samoa congressional districts": "countries/us/custom/us-as-congress-113.js",
        "Arizona congressional districts": "countries/us/custom/us-az-congress-113.js",
        "Arkansas congressional districts": "countries/us/custom/us-ar-congress-113.js",
        "California congressional districts": "countries/us/custom/us-ca-congress-113.js",
        "Colorado congressional districts": "countries/us/custom/us-co-congress-113.js",
        "Connecticut congressional districts": "countries/us/custom/us-ct-congress-113.js",
        "Delaware congressional districts": "countries/us/custom/us-de-congress-113.js",
        "District of Columbia congressional districts": "countries/us/custom/us-dc-congress-113.js",
        "Florida congressional districts": "countries/us/custom/us-fl-congress-113.js",
        "Georgia congressional districts": "countries/us/custom/us-ga-congress-113.js",
        "Guam congressional districts": "countries/us/custom/us-gu-congress-113.js",
        "Hawaii congressional districts": "countries/us/custom/us-hi-congress-113.js",
        "Idaho congressional districts": "countries/us/custom/us-id-congress-113.js",
        "Illinois congressional districts": "countries/us/custom/us-il-congress-113.js",
        "Indiana congressional districts": "countries/us/custom/us-in-congress-113.js",
        "Iowa congressional districts": "countries/us/custom/us-ia-congress-113.js",
        "Kansas congressional districts": "countries/us/custom/us-ks-congress-113.js",
        "Kentucky congressional districts": "countries/us/custom/us-ky-congress-113.js",
        "Louisiana congressional districts": "countries/us/custom/us-la-congress-113.js",
        "Maine congressional districts": "countries/us/custom/us-me-congress-113.js",
        "Maryland congressional districts": "countries/us/custom/us-md-congress-113.js",
        "Massachusetts congressional districts": "countries/us/custom/us-ma-congress-113.js",
        "Michigan congressional districts": "countries/us/custom/us-mi-congress-113.js",
        "Minnesota congressional districts": "countries/us/custom/us-mn-congress-113.js",
        "Mississippi congressional districts": "countries/us/custom/us-ms-congress-113.js",
        "Missouri congressional districts": "countries/us/custom/us-mo-congress-113.js",
        "Montana congressional districts": "countries/us/custom/us-mt-congress-113.js",
        "Nebraska congressional districts": "countries/us/custom/us-ne-congress-113.js",
        "Nevada congressional districts": "countries/us/custom/us-nv-congress-113.js",
        "New Hampshire congressional districts": "countries/us/custom/us-nh-congress-113.js",
        "New Jersey congressional districts": "countries/us/custom/us-nj-congress-113.js",
        "New Mexico congressional districts": "countries/us/custom/us-nm-congress-113.js",
        "New York congressional districts": "countries/us/custom/us-ny-congress-113.js",
        "North Carolina congressional districts": "countries/us/custom/us-nc-congress-113.js",
        "North Dakota congressional districts": "countries/us/custom/us-nd-congress-113.js",
        "Northern Mariana Islands congressional districts": "countries/us/custom/us-mp-congress-113.js",
        "Ohio congressional districts": "countries/us/custom/us-oh-congress-113.js",
        "Oklahoma congressional districts": "countries/us/custom/us-ok-congress-113.js",
        "Oregon congressional districts": "countries/us/custom/us-or-congress-113.js",
        "Pennsylvania congressional districts": "countries/us/custom/us-pa-congress-113.js",
        "Puerto Rico congressional districts": "countries/us/custom/us-pr-congress-113.js",
        "Rhode Island congressional districts": "countries/us/custom/us-ri-congress-113.js",
        "South Carolina congressional districts": "countries/us/custom/us-sc-congress-113.js",
        "South Dakota congressional districts": "countries/us/custom/us-sd-congress-113.js",
        "Tennessee congressional districts": "countries/us/custom/us-tn-congress-113.js",
        "Texas congressional districts": "countries/us/custom/us-tx-congress-113.js",
        "Utah congressional districts": "countries/us/custom/us-ut-congress-113.js",
        "Vermont congressional districts": "countries/us/custom/us-vt-congress-113.js",
        "Virginia congressional districts": "countries/us/custom/us-va-congress-113.js",
        "Washington congressional districts": "countries/us/custom/us-wa-congress-113.js",
        "West Virginia congressional districts": "countries/us/custom/us-wv-congress-113.js",
        "Wisconsin congressional districts": "countries/us/custom/us-wi-congress-113.js",
        "Wyoming congressional districts": "countries/us/custom/us-wy-congress-113.js"
    }
};